// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.22
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\pnmt1054\Adithya_working_directory\QT_PROJECTS\INDIGIS_DEPS\OpenDDS-3.33.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:372


#include "MessagerTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"
// TAO_IDL - Generated from
// C:\Users\pnmt1054\Adithya_working_directory\QT_PROJECTS\INDIGIS_DEPS\OpenDDS-3.33.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messager::MessageTypeSupport.

Messager::MessageTypeSupport_ptr
TAO::Objref_Traits<Messager::MessageTypeSupport>::duplicate (
    Messager::MessageTypeSupport_ptr p)
{
  return Messager::MessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Messager::MessageTypeSupport>::release (
    Messager::MessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Messager::MessageTypeSupport_ptr
TAO::Objref_Traits<Messager::MessageTypeSupport>::nil (void)
{
  return Messager::MessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messager::MessageTypeSupport>::marshal (
    const Messager::MessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messager::MessageTypeSupport::MessageTypeSupport (void)
{}

Messager::MessageTypeSupport::~MessageTypeSupport (void)
{
}

Messager::MessageTypeSupport_ptr
Messager::MessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

Messager::MessageTypeSupport_ptr
Messager::MessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

Messager::MessageTypeSupport_ptr
Messager::MessageTypeSupport::_nil (void)
{
  return 0;
}

Messager::MessageTypeSupport_ptr
Messager::MessageTypeSupport::_duplicate (MessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messager::MessageTypeSupport::_tao_release (MessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messager::MessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Messager/MessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messager::MessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Messager/MessageTypeSupport:1.0";
}

::CORBA::Boolean
Messager::MessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\pnmt1054\Adithya_working_directory\QT_PROJECTS\INDIGIS_DEPS\OpenDDS-3.33.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messager::MessageDataWriter.

Messager::MessageDataWriter_ptr
TAO::Objref_Traits<Messager::MessageDataWriter>::duplicate (
    Messager::MessageDataWriter_ptr p)
{
  return Messager::MessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Messager::MessageDataWriter>::release (
    Messager::MessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Messager::MessageDataWriter_ptr
TAO::Objref_Traits<Messager::MessageDataWriter>::nil (void)
{
  return Messager::MessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messager::MessageDataWriter>::marshal (
    const Messager::MessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messager::MessageDataWriter::MessageDataWriter (void)
{}

Messager::MessageDataWriter::~MessageDataWriter (void)
{
}

Messager::MessageDataWriter_ptr
Messager::MessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

Messager::MessageDataWriter_ptr
Messager::MessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

Messager::MessageDataWriter_ptr
Messager::MessageDataWriter::_nil (void)
{
  return 0;
}

Messager::MessageDataWriter_ptr
Messager::MessageDataWriter::_duplicate (MessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messager::MessageDataWriter::_tao_release (MessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messager::MessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Messager/MessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messager::MessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:Messager/MessageDataWriter:1.0";
}

::CORBA::Boolean
Messager::MessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// C:\Users\pnmt1054\Adithya_working_directory\QT_PROJECTS\INDIGIS_DEPS\OpenDDS-3.33.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messager::MessageDataReader.

Messager::MessageDataReader_ptr
TAO::Objref_Traits<Messager::MessageDataReader>::duplicate (
    Messager::MessageDataReader_ptr p)
{
  return Messager::MessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Messager::MessageDataReader>::release (
    Messager::MessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

Messager::MessageDataReader_ptr
TAO::Objref_Traits<Messager::MessageDataReader>::nil (void)
{
  return Messager::MessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messager::MessageDataReader>::marshal (
    const Messager::MessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messager::MessageDataReader::MessageDataReader (void)
{}

Messager::MessageDataReader::~MessageDataReader (void)
{
}

Messager::MessageDataReader_ptr
Messager::MessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

Messager::MessageDataReader_ptr
Messager::MessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

Messager::MessageDataReader_ptr
Messager::MessageDataReader::_nil (void)
{
  return 0;
}

Messager::MessageDataReader_ptr
Messager::MessageDataReader::_duplicate (MessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messager::MessageDataReader::_tao_release (MessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messager::MessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Messager/MessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messager::MessageDataReader::_interface_repository_id (void) const
{
  return "IDL:Messager/MessageDataReader:1.0";
}

::CORBA::Boolean
Messager::MessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

