// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.22
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\pnmt1054\Adithya_working_directory\QT_PROJECTS\INDIGIS_DEPS\OpenDDS-3.33.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:631

#ifndef _TAO_IDL_MESSAGERS_THV1V1_CPP_
#define _TAO_IDL_MESSAGERS_THV1V1_CPP_


#include "MessagerS.h"

#endif /* ifndef */

